stages:
  - test
  - delivery

test python:
  stage: test
  script:
    - docker compose -f docker/test/docker-compose.yml down
    - docker compose -f docker/test/docker-compose.yml build codeforcer_python
    - docker compose -f docker/test/docker-compose.yml up --abort-on-container-exit

delivery-job:
  stage: delivery
  dependencies:
    - test python
  script:
    - docker login -p $DOCKER_REGISTRY_KEY -u $DOCKER_REGISTRY_USER mashfeii
    - docker tag codeforcer:test $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE
