stages:
  - lint
  - test

pylint:
  stage: lint
  image: python:3.12
  variables:
    PYTHONPATH: "${PYTHONPATH}:backend/src" 
  before_script:
    - pip install -r backend/src/requirements.txt
    - pip install pylint
  script:
     - pylint backend/src --disable=C0114,C0116,R0903,C0115,C0103 --max-line-length=120
  only:
    - merge_requests
    - main

pytest:
  stage: test
  image: python:3.12
  variables:
     PYTHONPATH: "${PYTHONPATH}:backend/src"
  before_script:
    - pip install -r backend/src/requirements.txt
    - pip install pytest
  script:
    - pytest backend/src/tests/
  only:
    - merge_requests
    - main