stages:
  - test
  - delivery

test python:
  stage: test
  script:
    - docker compose -f docker/test/docker-compose.yml down
    - docker compose -f docker/test/docker-compose.yml build codeforcer
    - docker compose -f docker/test/docker-compose.yml up --abort-on-container-exit

delivery-job:
  stage: delivery
  dependencies:
    - test python
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_LOGIN --password-stdin
    - docker tag codeforcer:test $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE
