services:
  back:
    container_name: back
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - db:/code
  web:
    container_name: web
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - back
    ports:
      - "80:80"
    develop:
      watch:
        - action: rebuild
          path: ./frontend/
          target: /usr/share/nginx/html
          ignore:
            - node_modules/
            - dist/

volumes:
  db:
    driver: local
