services:
  back:
    container_name: back
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8000"
  web:
    container_name: web
    env_file:
      - frontend/.env
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - back
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /app/node_modules
      - ./frontend:/app
